-- 商品表
CREATE TABLE `product` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `delete_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `del_state` tinyint NOT NULL DEFAULT '0' COMMENT '删除状态，0-未删除，1-已删除',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  `category_id` bigint NOT NULL DEFAULT '0' COMMENT '商品所属分类id',
  `title` varchar(32) NOT NULL DEFAULT '' COMMENT '商品标题',
  `sub_title` varchar(128) NOT NULL DEFAULT '' COMMENT '商品副标题',
  `banner` varchar(4096) NOT NULL DEFAULT '' COMMENT '商品轮播图，第一张图是封面，使用"，"区分每个图片地址',
  `introduction` varchar(4096) NOT NULL DEFAULT '' COMMENT '商品介绍',
  `price` bigint NOT NULL DEFAULT '0' COMMENT '商品价格（分）',
  `discount_price` bigint NOT NULL DEFAULT '0' COMMENT '折扣价格（分）',
  `on_sale` tinyint (1) NOT NULL DEFAULT '0' COMMENT '0-下架，1-上架售卖，2-缺货中',
  `stock` bigint NOT NULL DEFAULT '0' COMMENT '库存',
  `sell_count` bigint NOT NULL DEFAULT '0' COMMENT '销售数量',
  `score` int unsigned NOT NULL DEFAULT '0' COMMENT '商品评分',
  `comment_count` int unsigned NOT NULL DEFAULT '0' COMMENT '评论数量',
  `store_id` bigint NOT NULL DEFAULT '0' COMMENT '店铺id',
  `boss_id` bigint NOT NULL DEFAULT '0' COMMENT '店主id',
  PRIMARY KEY (`id`),
  KEY `ix_category_id` (`category_id`),
  KEY `ix_store_id` (`store_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
