// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type AddProductToCartReq struct {
	ProductID int64 `json:"productId"`
	Count     int64 `json:"count"`
}

type AddProductToCartResp struct {
}

type CartProduct struct {
	ID            int64  `json:"id"`
	ProductID     int64  `json:"productId"`
	Title         string `json:"title"`
	Banner        string `json:"banner"`
	Price         int64  `json:"price"`
	DiscountPrice int64  `json:"discountPrice"`
	Count         int64  `json:"count"`
	Checked       int64  `json:"checked"`
}

type CartProductListReq struct {
}

type CartProductListResp struct {
	CartProducts []CartProduct `json:"cartProducts"`
}

type DeleteProductFromCartReq struct {
	CartID int64 `json:"cartId"`
}

type DeleteProductFromCartResp struct {
}

type UpdateProductDetailReq struct {
	CartID int64 `json:"cartId"`
	Count  int64 `json:"count"`
	Check  int64 `json:"check"`
}

type UpdateProductDetailResp struct {
}
