// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"github.com/mirage208/gomall/app/order/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 创建订单
				Method:  http.MethodPost,
				Path:    "/api/order/create",
				Handler: CreateHandler(serverCtx),
			},
			{
				// 获取订单详情
				Method:  http.MethodPost,
				Path:    "/api/order/detail",
				Handler: DetailHandler(serverCtx),
			},
			{
				// 获取订单列表
				Method:  http.MethodPost,
				Path:    "/api/order/list",
				Handler: ListHandler(serverCtx),
			},
			{
				// 删除订单
				Method:  http.MethodPost,
				Path:    "/api/order/remove",
				Handler: RemoveHandler(serverCtx),
			},
			{
				// 更新订单
				Method:  http.MethodPost,
				Path:    "/api/order/update",
				Handler: UpdateHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
