CREATE TABLE `third_payment` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `sn` varchar(64) NOT NULL DEFAULT '' COMMENT '流水单号',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `delete_time` timestamp NOT NULL DEFAULT '1970-01-01 00:00:01' COMMENT '删除时间',
    `del_state` tinyint (4) NOT NULL DEFAULT '0' COMMENT '删除状态 0:未删除 1:已删除',
    `version` bigint(20) NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
    `user_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '用户ID',
    `pay_mode` varchar(32) NOT NULL DEFAULT '' COMMENT '支付方式 1:微信支付',
    `trade_type` varchar(32) NOT NULL DEFAULT '' COMMENT '第三方支付类型',
    `trade_state` varchar(32) NOT NULL DEFAULT '' COMMENT '第三方交易状态',
    `pay_total` bigint(20) NOT NULL DEFAULT '0' COMMENT '支付总金额(分)',
    `transaction_id` varchar(64) NOT NULL DEFAULT '' COMMENT '第三方支付单号',
    `trade_state_desc` varchar(256) NOT NULL DEFAULT '' COMMENT '支付状态描述',
    `order_sn` varchar(64) NOT NULL DEFAULT '' COMMENT '业务单号',
    `service_type` varchar(32) NOT NULL DEFAULT '' COMMENT '业务类型',
    `pay_status` tinyint (4) NOT NULL DEFAULT '0' COMMENT '平台内交易状态 -1:支付失败 0:未支付 1:支付成功 2:已退款',
    `pay_time` timestamp NOT NULL DEFAULT '1970-01-01 00:00:01' COMMENT '支付成功时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_sn` (`sn`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_order_sn` (`order_sn`),
    KEY `idx_transaction_id` (`transaction_id`),
    KEY `idx_pay_status` (`pay_status`),
    KEY `idx_del_state` (`del_state`),
    KEY `idx_create_time` (`create_time`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '第三方支付记录表';