// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: cart.proto

package server

import (
	"context"

	"github.com/mirage208/gomall/app/cart/rpc/internal/logic"
	"github.com/mirage208/gomall/app/cart/rpc/internal/svc"
	"github.com/mirage208/gomall/app/cart/rpc/pb/cart"
)

type CartServer struct {
	svcCtx *svc.ServiceContext
	cart.UnimplementedCartServer
}

func NewCartServer(svcCtx *svc.ServiceContext) *CartServer {
	return &CartServer{
		svcCtx: svcCtx,
	}
}

func (s *CartServer) AddProductToCart(ctx context.Context, in *cart.AddProductToCartReq) (*cart.AddProductToCartResp, error) {
	l := logic.NewAddProductToCartLogic(ctx, s.svcCtx)
	return l.AddProductToCart(in)
}

func (s *CartServer) CartProductList(ctx context.Context, in *cart.CartProductListReq) (*cart.CartProductListResp, error) {
	l := logic.NewCartProductListLogic(ctx, s.svcCtx)
	return l.CartProductList(in)
}

func (s *CartServer) DeleteProductFromCart(ctx context.Context, in *cart.DeleteProductFromCartReq) (*cart.DeleteProductFromCartResp, error) {
	l := logic.NewDeleteProductFromCartLogic(ctx, s.svcCtx)
	return l.DeleteProductFromCart(in)
}

func (s *CartServer) UpdateProductDetail(ctx context.Context, in *cart.UpdateProductDetailReq) (*cart.UpdateProductDetailResp, error) {
	l := logic.NewUpdateProductDetailLogic(ctx, s.svcCtx)
	return l.UpdateProductDetail(in)
}
