// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: order.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ID               int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CreateTime       string                 `protobuf:"bytes,2,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime       string                 `protobuf:"bytes,3,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	OrderSn          string                 `protobuf:"bytes,4,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`
	UserID           int64                  `protobuf:"varint,5,opt,name=UserID,proto3" json:"UserID,omitempty"`
	AddressDetail    string                 `protobuf:"bytes,6,opt,name=AddressDetail,proto3" json:"AddressDetail,omitempty"`
	AddressPhoneName string                 `protobuf:"bytes,7,opt,name=AddressPhoneName,proto3" json:"AddressPhoneName,omitempty"`
	ProductID        int64                  `protobuf:"varint,8,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	Title            string                 `protobuf:"bytes,9,opt,name=Title,proto3" json:"Title,omitempty"`
	SubTitle         string                 `protobuf:"bytes,10,opt,name=SubTitle,proto3" json:"SubTitle,omitempty"`
	Banner           string                 `protobuf:"bytes,11,opt,name=Banner,proto3" json:"Banner,omitempty"`
	Info             string                 `protobuf:"bytes,12,opt,name=Info,proto3" json:"Info,omitempty"`
	ProductStoreID   int64                  `protobuf:"varint,13,opt,name=ProductStoreID,proto3" json:"ProductStoreID,omitempty"`
	ProductBossID    int64                  `protobuf:"varint,14,opt,name=ProductBossID,proto3" json:"ProductBossID,omitempty"`
	ProductCount     int64                  `protobuf:"varint,15,opt,name=ProductCount,proto3" json:"ProductCount,omitempty"`
	UnitPrice        int64                  `protobuf:"varint,16,opt,name=UnitPrice,proto3" json:"UnitPrice,omitempty"`
	TotalPrice       int64                  `protobuf:"varint,17,opt,name=TotalPrice,proto3" json:"TotalPrice,omitempty"`
	Status           int64                  `protobuf:"varint,18,opt,name=Status,proto3" json:"Status,omitempty"`
	Remark           string                 `protobuf:"bytes,19,opt,name=Remark,proto3" json:"Remark,omitempty"`
	PayTime          string                 `protobuf:"bytes,20,opt,name=PayTime,proto3" json:"PayTime,omitempty"`
	PayType          string                 `protobuf:"bytes,21,opt,name=PayType,proto3" json:"PayType,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Order) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *Order) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *Order) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *Order) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *Order) GetAddressDetail() string {
	if x != nil {
		return x.AddressDetail
	}
	return ""
}

func (x *Order) GetAddressPhoneName() string {
	if x != nil {
		return x.AddressPhoneName
	}
	return ""
}

func (x *Order) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *Order) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Order) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

func (x *Order) GetBanner() string {
	if x != nil {
		return x.Banner
	}
	return ""
}

func (x *Order) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *Order) GetProductStoreID() int64 {
	if x != nil {
		return x.ProductStoreID
	}
	return 0
}

func (x *Order) GetProductBossID() int64 {
	if x != nil {
		return x.ProductBossID
	}
	return 0
}

func (x *Order) GetProductCount() int64 {
	if x != nil {
		return x.ProductCount
	}
	return 0
}

func (x *Order) GetUnitPrice() int64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *Order) GetTotalPrice() int64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Order) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Order) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *Order) GetPayTime() string {
	if x != nil {
		return x.PayTime
	}
	return ""
}

func (x *Order) GetPayType() string {
	if x != nil {
		return x.PayType
	}
	return ""
}

type CreateOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	ProductID     int64                  `protobuf:"varint,2,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	UserAddressID int64                  `protobuf:"varint,3,opt,name=UserAddressID,proto3" json:"UserAddressID,omitempty"`
	ProductCount  int64                  `protobuf:"varint,4,opt,name=ProductCount,proto3" json:"ProductCount,omitempty"`
	Remark        string                 `protobuf:"bytes,5,opt,name=Remark,proto3" json:"Remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *CreateOrderReq) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *CreateOrderReq) GetUserAddressID() int64 {
	if x != nil {
		return x.UserAddressID
	}
	return 0
}

func (x *CreateOrderReq) GetProductCount() int64 {
	if x != nil {
		return x.ProductCount
	}
	return 0
}

func (x *CreateOrderReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type CreateOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            string                 `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResp) Reset() {
	*x = CreateOrderResp{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResp) ProtoMessage() {}

func (x *CreateOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResp.ProtoReflect.Descriptor instead.
func (*CreateOrderResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderResp) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

type OrderDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	SN            string                 `protobuf:"bytes,2,opt,name=SN,proto3" json:"SN,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDetailReq) Reset() {
	*x = OrderDetailReq{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetailReq) ProtoMessage() {}

func (x *OrderDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetailReq.ProtoReflect.Descriptor instead.
func (*OrderDetailReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *OrderDetailReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *OrderDetailReq) GetSN() string {
	if x != nil {
		return x.SN
	}
	return ""
}

type OrderDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDetailResp) Reset() {
	*x = OrderDetailResp{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetailResp) ProtoMessage() {}

func (x *OrderDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetailResp.ProtoReflect.Descriptor instead.
func (*OrderDetailResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *OrderDetailResp) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type UpdateOrderTradeStateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       string                 `protobuf:"bytes,1,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`
	TradeState    int64                  `protobuf:"varint,2,opt,name=tradeState,proto3" json:"tradeState,omitempty"` //-1: 已取消 0:待支付 1:未使用 2:已使用  3:已过关闭
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderTradeStateReq) Reset() {
	*x = UpdateOrderTradeStateReq{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderTradeStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderTradeStateReq) ProtoMessage() {}

func (x *UpdateOrderTradeStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderTradeStateReq.ProtoReflect.Descriptor instead.
func (*UpdateOrderTradeStateReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateOrderTradeStateReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *UpdateOrderTradeStateReq) GetTradeState() int64 {
	if x != nil {
		return x.TradeState
	}
	return 0
}

type UpdateOrderTradeStateResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ID              int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID          int64                  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	OrderSn         string                 `protobuf:"bytes,3,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`
	TradeCode       string                 `protobuf:"bytes,4,opt,name=TradeCode,proto3" json:"TradeCode,omitempty"`
	LiveStartDate   int64                  `protobuf:"varint,5,opt,name=LiveStartDate,proto3" json:"LiveStartDate,omitempty"`
	LiveEndDate     int64                  `protobuf:"varint,6,opt,name=LiveEndDate,proto3" json:"LiveEndDate,omitempty"`
	OrderTotalPrice int64                  `protobuf:"varint,7,opt,name=OrderTotalPrice,proto3" json:"OrderTotalPrice,omitempty"`
	Title           string                 `protobuf:"bytes,8,opt,name=Title,proto3" json:"Title,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateOrderTradeStateResp) Reset() {
	*x = UpdateOrderTradeStateResp{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderTradeStateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderTradeStateResp) ProtoMessage() {}

func (x *UpdateOrderTradeStateResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderTradeStateResp.ProtoReflect.Descriptor instead.
func (*UpdateOrderTradeStateResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateOrderTradeStateResp) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *UpdateOrderTradeStateResp) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UpdateOrderTradeStateResp) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *UpdateOrderTradeStateResp) GetTradeCode() string {
	if x != nil {
		return x.TradeCode
	}
	return ""
}

func (x *UpdateOrderTradeStateResp) GetLiveStartDate() int64 {
	if x != nil {
		return x.LiveStartDate
	}
	return 0
}

func (x *UpdateOrderTradeStateResp) GetLiveEndDate() int64 {
	if x != nil {
		return x.LiveEndDate
	}
	return 0
}

func (x *UpdateOrderTradeStateResp) GetOrderTotalPrice() int64 {
	if x != nil {
		return x.OrderTotalPrice
	}
	return 0
}

func (x *UpdateOrderTradeStateResp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type UserOrderListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastId        int64                  `protobuf:"varint,1,opt,name=lastId,proto3" json:"lastId,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	TraderState   int64                  `protobuf:"varint,4,opt,name=traderState,proto3" json:"traderState,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOrderListReq) Reset() {
	*x = UserOrderListReq{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOrderListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOrderListReq) ProtoMessage() {}

func (x *UserOrderListReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOrderListReq.ProtoReflect.Descriptor instead.
func (*UserOrderListReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *UserOrderListReq) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *UserOrderListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *UserOrderListReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserOrderListReq) GetTraderState() int64 {
	if x != nil {
		return x.TraderState
	}
	return 0
}

type UserOrderListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Order               `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOrderListResp) Reset() {
	*x = UserOrderListResp{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOrderListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOrderListResp) ProtoMessage() {}

func (x *UserOrderListResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOrderListResp.ProtoReflect.Descriptor instead.
func (*UserOrderListResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *UserOrderListResp) GetList() []*Order {
	if x != nil {
		return x.List
	}
	return nil
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x05order\"\xeb\x04\n" +
	"\x05Order\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x1e\n" +
	"\n" +
	"CreateTime\x18\x02 \x01(\tR\n" +
	"CreateTime\x12\x1e\n" +
	"\n" +
	"UpdateTime\x18\x03 \x01(\tR\n" +
	"UpdateTime\x12\x18\n" +
	"\aOrderSn\x18\x04 \x01(\tR\aOrderSn\x12\x16\n" +
	"\x06UserID\x18\x05 \x01(\x03R\x06UserID\x12$\n" +
	"\rAddressDetail\x18\x06 \x01(\tR\rAddressDetail\x12*\n" +
	"\x10AddressPhoneName\x18\a \x01(\tR\x10AddressPhoneName\x12\x1c\n" +
	"\tProductID\x18\b \x01(\x03R\tProductID\x12\x14\n" +
	"\x05Title\x18\t \x01(\tR\x05Title\x12\x1a\n" +
	"\bSubTitle\x18\n" +
	" \x01(\tR\bSubTitle\x12\x16\n" +
	"\x06Banner\x18\v \x01(\tR\x06Banner\x12\x12\n" +
	"\x04Info\x18\f \x01(\tR\x04Info\x12&\n" +
	"\x0eProductStoreID\x18\r \x01(\x03R\x0eProductStoreID\x12$\n" +
	"\rProductBossID\x18\x0e \x01(\x03R\rProductBossID\x12\"\n" +
	"\fProductCount\x18\x0f \x01(\x03R\fProductCount\x12\x1c\n" +
	"\tUnitPrice\x18\x10 \x01(\x03R\tUnitPrice\x12\x1e\n" +
	"\n" +
	"TotalPrice\x18\x11 \x01(\x03R\n" +
	"TotalPrice\x12\x16\n" +
	"\x06Status\x18\x12 \x01(\x03R\x06Status\x12\x16\n" +
	"\x06Remark\x18\x13 \x01(\tR\x06Remark\x12\x18\n" +
	"\aPayTime\x18\x14 \x01(\tR\aPayTime\x12\x18\n" +
	"\aPayType\x18\x15 \x01(\tR\aPayType\"\xa8\x01\n" +
	"\x0eCreateOrderReq\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\x12\x1c\n" +
	"\tProductID\x18\x02 \x01(\x03R\tProductID\x12$\n" +
	"\rUserAddressID\x18\x03 \x01(\x03R\rUserAddressID\x12\"\n" +
	"\fProductCount\x18\x04 \x01(\x03R\fProductCount\x12\x16\n" +
	"\x06Remark\x18\x05 \x01(\tR\x06Remark\"!\n" +
	"\x0fCreateOrderResp\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\tR\x02sn\"8\n" +
	"\x0eOrderDetailReq\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\x12\x0e\n" +
	"\x02SN\x18\x02 \x01(\tR\x02SN\"5\n" +
	"\x0fOrderDetailResp\x12\"\n" +
	"\x05order\x18\x01 \x01(\v2\f.order.OrderR\x05order\"T\n" +
	"\x18UpdateOrderTradeStateReq\x12\x18\n" +
	"\aOrderSn\x18\x01 \x01(\tR\aOrderSn\x12\x1e\n" +
	"\n" +
	"tradeState\x18\x02 \x01(\x03R\n" +
	"tradeState\"\x83\x02\n" +
	"\x19UpdateOrderTradeStateResp\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\x03R\x06UserID\x12\x18\n" +
	"\aOrderSn\x18\x03 \x01(\tR\aOrderSn\x12\x1c\n" +
	"\tTradeCode\x18\x04 \x01(\tR\tTradeCode\x12$\n" +
	"\rLiveStartDate\x18\x05 \x01(\x03R\rLiveStartDate\x12 \n" +
	"\vLiveEndDate\x18\x06 \x01(\x03R\vLiveEndDate\x12(\n" +
	"\x0fOrderTotalPrice\x18\a \x01(\x03R\x0fOrderTotalPrice\x12\x14\n" +
	"\x05Title\x18\b \x01(\tR\x05Title\"\x80\x01\n" +
	"\x10UserOrderListReq\x12\x16\n" +
	"\x06lastId\x18\x01 \x01(\x03R\x06lastId\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x03R\x06userId\x12 \n" +
	"\vtraderState\x18\x04 \x01(\x03R\vtraderState\"5\n" +
	"\x11UserOrderListResp\x12 \n" +
	"\x04list\x18\x01 \x03(\v2\f.order.OrderR\x04list2\xa3\x02\n" +
	"\x05order\x12<\n" +
	"\vcreateOrder\x12\x15.order.CreateOrderReq\x1a\x16.order.CreateOrderResp\x12<\n" +
	"\vOrderDetail\x12\x15.order.OrderDetailReq\x1a\x16.order.OrderDetailResp\x12Z\n" +
	"\x15updateOrderTradeState\x12\x1f.order.UpdateOrderTradeStateReq\x1a .order.UpdateOrderTradeStateResp\x12B\n" +
	"\ruserOrderList\x12\x17.order.UserOrderListReq\x1a\x18.order.UserOrderListRespB\tZ\a./orderb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_order_proto_goTypes = []any{
	(*Order)(nil),                     // 0: order.Order
	(*CreateOrderReq)(nil),            // 1: order.CreateOrderReq
	(*CreateOrderResp)(nil),           // 2: order.CreateOrderResp
	(*OrderDetailReq)(nil),            // 3: order.OrderDetailReq
	(*OrderDetailResp)(nil),           // 4: order.OrderDetailResp
	(*UpdateOrderTradeStateReq)(nil),  // 5: order.UpdateOrderTradeStateReq
	(*UpdateOrderTradeStateResp)(nil), // 6: order.UpdateOrderTradeStateResp
	(*UserOrderListReq)(nil),          // 7: order.UserOrderListReq
	(*UserOrderListResp)(nil),         // 8: order.UserOrderListResp
}
var file_order_proto_depIdxs = []int32{
	0, // 0: order.OrderDetailResp.order:type_name -> order.Order
	0, // 1: order.UserOrderListResp.list:type_name -> order.Order
	1, // 2: order.order.createOrder:input_type -> order.CreateOrderReq
	3, // 3: order.order.OrderDetail:input_type -> order.OrderDetailReq
	5, // 4: order.order.updateOrderTradeState:input_type -> order.UpdateOrderTradeStateReq
	7, // 5: order.order.userOrderList:input_type -> order.UserOrderListReq
	2, // 6: order.order.createOrder:output_type -> order.CreateOrderResp
	4, // 7: order.order.OrderDetail:output_type -> order.OrderDetailResp
	6, // 8: order.order.updateOrderTradeState:output_type -> order.UpdateOrderTradeStateResp
	8, // 9: order.order.userOrderList:output_type -> order.UserOrderListResp
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
