// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderPaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	OrderSn       string                 `protobuf:"bytes,2,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`
	ServiceType   int64                  `protobuf:"varint,3,opt,name=ServiceType,proto3" json:"ServiceType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPaymentReq) Reset() {
	*x = OrderPaymentReq{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPaymentReq) ProtoMessage() {}

func (x *OrderPaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPaymentReq.ProtoReflect.Descriptor instead.
func (*OrderPaymentReq) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *OrderPaymentReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *OrderPaymentReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *OrderPaymentReq) GetServiceType() int64 {
	if x != nil {
		return x.ServiceType
	}
	return 0
}

type OrderPaymentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayTotalPrice int64                  `protobuf:"varint,1,opt,name=PayTotalPrice,proto3" json:"PayTotalPrice,omitempty"`
	PaySn         string                 `protobuf:"bytes,2,opt,name=PaySn,proto3" json:"PaySn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPaymentResp) Reset() {
	*x = OrderPaymentResp{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPaymentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPaymentResp) ProtoMessage() {}

func (x *OrderPaymentResp) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPaymentResp.ProtoReflect.Descriptor instead.
func (*OrderPaymentResp) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *OrderPaymentResp) GetPayTotalPrice() int64 {
	if x != nil {
		return x.PayTotalPrice
	}
	return 0
}

func (x *OrderPaymentResp) GetPaySn() string {
	if x != nil {
		return x.PaySn
	}
	return ""
}

type GetPaymentDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       string                 `protobuf:"bytes,1,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentDetailReq) Reset() {
	*x = GetPaymentDetailReq{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentDetailReq) ProtoMessage() {}

func (x *GetPaymentDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentDetailReq.ProtoReflect.Descriptor instead.
func (*GetPaymentDetailReq) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *GetPaymentDetailReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

type GetPaymentDetailResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ID             int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PaymentSn      string                 `protobuf:"bytes,2,opt,name=PaymentSn,proto3" json:"PaymentSn,omitempty"`
	OrderSn        string                 `protobuf:"bytes,3,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`
	UserID         int64                  `protobuf:"varint,4,opt,name=UserID,proto3" json:"UserID,omitempty"`
	PayMode        int64                  `protobuf:"varint,5,opt,name=PayMode,proto3" json:"PayMode,omitempty"`
	TradeType      string                 `protobuf:"bytes,6,opt,name=TradeType,proto3" json:"TradeType,omitempty"`
	TradeState     string                 `protobuf:"bytes,7,opt,name=TradeState,proto3" json:"TradeState,omitempty"`
	PayTotal       int64                  `protobuf:"varint,8,opt,name=PayTotal,proto3" json:"PayTotal,omitempty"`
	TransactionID  string                 `protobuf:"bytes,9,opt,name=TransactionID,proto3" json:"TransactionID,omitempty"`
	TradeStateDesc string                 `protobuf:"bytes,10,opt,name=TradeStateDesc,proto3" json:"TradeStateDesc,omitempty"`
	PayStatus      int64                  `protobuf:"varint,11,opt,name=PayStatus,proto3" json:"PayStatus,omitempty"`
	PayTime        string                 `protobuf:"bytes,12,opt,name=PayTime,proto3" json:"PayTime,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPaymentDetailResp) Reset() {
	*x = GetPaymentDetailResp{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentDetailResp) ProtoMessage() {}

func (x *GetPaymentDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentDetailResp.ProtoReflect.Descriptor instead.
func (*GetPaymentDetailResp) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *GetPaymentDetailResp) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *GetPaymentDetailResp) GetPaymentSn() string {
	if x != nil {
		return x.PaymentSn
	}
	return ""
}

func (x *GetPaymentDetailResp) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *GetPaymentDetailResp) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetPaymentDetailResp) GetPayMode() int64 {
	if x != nil {
		return x.PayMode
	}
	return 0
}

func (x *GetPaymentDetailResp) GetTradeType() string {
	if x != nil {
		return x.TradeType
	}
	return ""
}

func (x *GetPaymentDetailResp) GetTradeState() string {
	if x != nil {
		return x.TradeState
	}
	return ""
}

func (x *GetPaymentDetailResp) GetPayTotal() int64 {
	if x != nil {
		return x.PayTotal
	}
	return 0
}

func (x *GetPaymentDetailResp) GetTransactionID() string {
	if x != nil {
		return x.TransactionID
	}
	return ""
}

func (x *GetPaymentDetailResp) GetTradeStateDesc() string {
	if x != nil {
		return x.TradeStateDesc
	}
	return ""
}

func (x *GetPaymentDetailResp) GetPayStatus() int64 {
	if x != nil {
		return x.PayStatus
	}
	return 0
}

func (x *GetPaymentDetailResp) GetPayTime() string {
	if x != nil {
		return x.PayTime
	}
	return ""
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\apayment\"e\n" +
	"\x0fOrderPaymentReq\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\x12\x18\n" +
	"\aOrderSn\x18\x02 \x01(\tR\aOrderSn\x12 \n" +
	"\vServiceType\x18\x03 \x01(\x03R\vServiceType\"N\n" +
	"\x10OrderPaymentResp\x12$\n" +
	"\rPayTotalPrice\x18\x01 \x01(\x03R\rPayTotalPrice\x12\x14\n" +
	"\x05PaySn\x18\x02 \x01(\tR\x05PaySn\"/\n" +
	"\x13GetPaymentDetailReq\x12\x18\n" +
	"\aOrderSn\x18\x01 \x01(\tR\aOrderSn\"\xf0\x02\n" +
	"\x14GetPaymentDetailResp\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x1c\n" +
	"\tPaymentSn\x18\x02 \x01(\tR\tPaymentSn\x12\x18\n" +
	"\aOrderSn\x18\x03 \x01(\tR\aOrderSn\x12\x16\n" +
	"\x06UserID\x18\x04 \x01(\x03R\x06UserID\x12\x18\n" +
	"\aPayMode\x18\x05 \x01(\x03R\aPayMode\x12\x1c\n" +
	"\tTradeType\x18\x06 \x01(\tR\tTradeType\x12\x1e\n" +
	"\n" +
	"TradeState\x18\a \x01(\tR\n" +
	"TradeState\x12\x1a\n" +
	"\bPayTotal\x18\b \x01(\x03R\bPayTotal\x12$\n" +
	"\rTransactionID\x18\t \x01(\tR\rTransactionID\x12&\n" +
	"\x0eTradeStateDesc\x18\n" +
	" \x01(\tR\x0eTradeStateDesc\x12\x1c\n" +
	"\tPayStatus\x18\v \x01(\x03R\tPayStatus\x12\x18\n" +
	"\aPayTime\x18\f \x01(\tR\aPayTime2\x9f\x01\n" +
	"\apayment\x12C\n" +
	"\forderPayment\x12\x18.payment.OrderPaymentReq\x1a\x19.payment.OrderPaymentResp\x12O\n" +
	"\x10getPaymentDetail\x12\x1c.payment.GetPaymentDetailReq\x1a\x1d.payment.GetPaymentDetailRespB\vZ\t./paymentb\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_payment_proto_goTypes = []any{
	(*OrderPaymentReq)(nil),      // 0: payment.OrderPaymentReq
	(*OrderPaymentResp)(nil),     // 1: payment.OrderPaymentResp
	(*GetPaymentDetailReq)(nil),  // 2: payment.GetPaymentDetailReq
	(*GetPaymentDetailResp)(nil), // 3: payment.GetPaymentDetailResp
}
var file_payment_proto_depIdxs = []int32{
	0, // 0: payment.payment.orderPayment:input_type -> payment.OrderPaymentReq
	2, // 1: payment.payment.getPaymentDetail:input_type -> payment.GetPaymentDetailReq
	1, // 2: payment.payment.orderPayment:output_type -> payment.OrderPaymentResp
	3, // 3: payment.payment.getPaymentDetail:output_type -> payment.GetPaymentDetailResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
