// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type OrderPayReq struct {
	OrderSn     string `json:"orderSn"`
	ServiceType int64  `json:"serviceType"`
}

type OrderPayResp struct {
	PayTotalPrice float64 `json:"payTotalPrice"`
	PaySn         string  `json:"paySn"`
}
