// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: payment.proto

package server

import (
	"context"

	"github.com/mirage208/gomall/app/payment/rpc/internal/logic"
	"github.com/mirage208/gomall/app/payment/rpc/internal/svc"
	"github.com/mirage208/gomall/app/payment/rpc/pb/payment"
)

type PaymentServer struct {
	svcCtx *svc.ServiceContext
	payment.UnimplementedPaymentServer
}

func NewPaymentServer(svcCtx *svc.ServiceContext) *PaymentServer {
	return &PaymentServer{
		svcCtx: svcCtx,
	}
}

func (s *PaymentServer) OrderPayment(ctx context.Context, in *payment.OrderPaymentReq) (*payment.OrderPaymentResp, error) {
	l := logic.NewOrderPaymentLogic(ctx, s.svcCtx)
	return l.OrderPayment(in)
}

func (s *PaymentServer) GetPaymentDetail(ctx context.Context, in *payment.GetPaymentDetailReq) (*payment.GetPaymentDetailResp, error) {
	l := logic.NewGetPaymentDetailLogic(ctx, s.svcCtx)
	return l.GetPaymentDetail(in)
}
