// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: payment.proto

package server

import (
	"context"

	"github.com/mirage208/gomall/app/payment/rpc/internal/logic"
	"github.com/mirage208/gomall/app/payment/rpc/internal/svc"
	"github.com/mirage208/gomall/app/payment/rpc/pb/payment"
)

type PaymentServer struct {
	svcCtx *svc.ServiceContext
	payment.UnimplementedPaymentServer
}

func NewPaymentServer(svcCtx *svc.ServiceContext) *PaymentServer {
	return &PaymentServer{
		svcCtx: svcCtx,
	}
}

func (s *PaymentServer) Create(ctx context.Context, in *payment.CreateRequest) (*payment.CreateResponse, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *PaymentServer) Detail(ctx context.Context, in *payment.DetailRequest) (*payment.DetailResponse, error) {
	l := logic.NewDetailLogic(ctx, s.svcCtx)
	return l.Detail(in)
}

func (s *PaymentServer) Callback(ctx context.Context, in *payment.CallbackRequest) (*payment.CallbackResponse, error) {
	l := logic.NewCallbackLogic(ctx, s.svcCtx)
	return l.Callback(in)
}
