// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: payment.proto

package server

import (
	"context"

	"github.com/mirage208/gomall/app/payment/rpc/internal/logic"
	"github.com/mirage208/gomall/app/payment/rpc/internal/svc"
	"github.com/mirage208/gomall/app/payment/rpc/pb/payment"
)

type PaymentServer struct {
	svcCtx *svc.ServiceContext
	payment.UnimplementedPaymentServer
}

func NewPaymentServer(svcCtx *svc.ServiceContext) *PaymentServer {
	return &PaymentServer{
		svcCtx: svcCtx,
	}
}

// 创建微信支付预处理订单
func (s *PaymentServer) CreatePayment(ctx context.Context, in *payment.CreatePaymentReq) (*payment.CreatePaymentResp, error) {
	l := logic.NewCreatePaymentLogic(ctx, s.svcCtx)
	return l.CreatePayment(in)
}

// 根据sn查询流水记录
func (s *PaymentServer) GetPaymentBySn(ctx context.Context, in *payment.GetPaymentBySnReq) (*payment.GetPaymentBySnResp, error) {
	l := logic.NewGetPaymentBySnLogic(ctx, s.svcCtx)
	return l.GetPaymentBySn(in)
}

// 更新交易状态
func (s *PaymentServer) UpdateTradeState(ctx context.Context, in *payment.UpdateTradeStateReq) (*payment.UpdateTradeStateResp, error) {
	l := logic.NewUpdateTradeStateLogic(ctx, s.svcCtx)
	return l.UpdateTradeState(in)
}

// 根据订单sn查询流水记录
func (s *PaymentServer) GetPaymentSuccessRefundByOrderSn(ctx context.Context, in *payment.GetPaymentSuccessRefundByOrderSnReq) (*payment.GetPaymentSuccessRefundByOrderSnResp, error) {
	l := logic.NewGetPaymentSuccessRefundByOrderSnLogic(ctx, s.svcCtx)
	return l.GetPaymentSuccessRefundByOrderSn(in)
}
