// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	cart "github.com/mirage208/gomall/app/cart/api/internal/handler/cart"
	"github.com/mirage208/gomall/app/cart/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CheckUserState},
			[]rest.Route{
				{
					// 添加商品到购物车
					Method:  http.MethodPost,
					Path:    "/cart",
					Handler: cart.AddProductToCartHandler(serverCtx),
				},
				{
					// 购物车商品列表
					Method:  http.MethodGet,
					Path:    "/cart",
					Handler: cart.CartProductListHandler(serverCtx),
				},
				{
					// 删除购物车商品
					Method:  http.MethodDelete,
					Path:    "/cart",
					Handler: cart.DeleteProductFromCartHandler(serverCtx),
				},
				{
					// 修改购物车商品的信息
					Method:  http.MethodPut,
					Path:    "/cart",
					Handler: cart.UpdateProductDetailHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/cart/v1"),
	)
}
