// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: user.proto

package userclient

import (
	"context"

	"github.com/mirage208/gomall/app/user/rpc/pb/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Address                       = user.Address
	CheckUserAndAddressExistsReq  = user.CheckUserAndAddressExistsReq
	CheckUserAndAddressExistsResp = user.CheckUserAndAddressExistsResp
	CheckUserExistsReq            = user.CheckUserExistsReq
	CheckUserExistsResp           = user.CheckUserExistsResp
	CreateUserAddressReq          = user.CreateUserAddressReq
	CreateUserAddressResp         = user.CreateUserAddressResp
	DeleteUserAddressReq          = user.DeleteUserAddressReq
	DeleteUserAddressResp         = user.DeleteUserAddressResp
	GenerateTokenReq              = user.GenerateTokenReq
	GenerateTokenResp             = user.GenerateTokenResp
	GetUserAddressDetailReq       = user.GetUserAddressDetailReq
	GetUserAddressDetailResp      = user.GetUserAddressDetailResp
	GetUserAddressListReq         = user.GetUserAddressListReq
	GetUserAddressListResp        = user.GetUserAddressListResp
	GetUserInfoReq                = user.GetUserInfoReq
	GetUserInfoResp               = user.GetUserInfoResp
	GetUserMoneyReq               = user.GetUserMoneyReq
	GetUserMoneyResp              = user.GetUserMoneyResp
	LoginReq                      = user.LoginReq
	LoginResp                     = user.LoginResp
	LogoutReq                     = user.LogoutReq
	LogoutResp                    = user.LogoutResp
	RegisterReq                   = user.RegisterReq
	RegisterResp                  = user.RegisterResp
	UpdateEmailReq                = user.UpdateEmailReq
	UpdateEmailResp               = user.UpdateEmailResp
	UpdatePasswordReq             = user.UpdatePasswordReq
	UpdatePasswordResp            = user.UpdatePasswordResp
	UpdateUserAddressReq          = user.UpdateUserAddressReq
	UpdateUserAddressResp         = user.UpdateUserAddressResp
	UpdateUserInfoReq             = user.UpdateUserInfoReq
	UpdateUserInfoResp            = user.UpdateUserInfoResp
	UpdateUserMoneyReq            = user.UpdateUserMoneyReq
	UpdateUserMoneyResp           = user.UpdateUserMoneyResp

	User interface {
		// user
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		GenerateToken(ctx context.Context, in *GenerateTokenReq, opts ...grpc.CallOption) (*GenerateTokenResp, error)
		Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResp, error)
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		UpdateEmail(ctx context.Context, in *UpdateEmailReq, opts ...grpc.CallOption) (*UpdateEmailResp, error)
		UpdatePassword(ctx context.Context, in *UpdatePasswordReq, opts ...grpc.CallOption) (*UpdatePasswordResp, error)
		UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*UpdateUserInfoResp, error)
		GetUserMoney(ctx context.Context, in *GetUserMoneyReq, opts ...grpc.CallOption) (*GetUserMoneyResp, error)
		// userAddress
		GetUserAddressList(ctx context.Context, in *GetUserAddressListReq, opts ...grpc.CallOption) (*GetUserAddressListResp, error)
		CreateUserAddress(ctx context.Context, in *CreateUserAddressReq, opts ...grpc.CallOption) (*CreateUserAddressResp, error)
		UpdateUserAddress(ctx context.Context, in *UpdateUserAddressReq, opts ...grpc.CallOption) (*UpdateUserAddressResp, error)
		DeleteUserAddress(ctx context.Context, in *DeleteUserAddressReq, opts ...grpc.CallOption) (*DeleteUserAddressResp, error)
		GetUserAddressDetail(ctx context.Context, in *GetUserAddressDetailReq, opts ...grpc.CallOption) (*GetUserAddressDetailResp, error)
		// other
		CheckUserExists(ctx context.Context, in *CheckUserExistsReq, opts ...grpc.CallOption) (*CheckUserExistsResp, error)
		CheckUserAndAddressExists(ctx context.Context, in *CheckUserAndAddressExistsReq, opts ...grpc.CallOption) (*CheckUserAndAddressExistsResp, error)
		UpdateUserMoney(ctx context.Context, in *UpdateUserMoneyReq, opts ...grpc.CallOption) (*UpdateUserMoneyResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

// user
func (m *defaultUser) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUser) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUser) GenerateToken(ctx context.Context, in *GenerateTokenReq, opts ...grpc.CallOption) (*GenerateTokenResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GenerateToken(ctx, in, opts...)
}

func (m *defaultUser) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

func (m *defaultUser) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultUser) UpdateEmail(ctx context.Context, in *UpdateEmailReq, opts ...grpc.CallOption) (*UpdateEmailResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateEmail(ctx, in, opts...)
}

func (m *defaultUser) UpdatePassword(ctx context.Context, in *UpdatePasswordReq, opts ...grpc.CallOption) (*UpdatePasswordResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdatePassword(ctx, in, opts...)
}

func (m *defaultUser) UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*UpdateUserInfoResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateUserInfo(ctx, in, opts...)
}

func (m *defaultUser) GetUserMoney(ctx context.Context, in *GetUserMoneyReq, opts ...grpc.CallOption) (*GetUserMoneyResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserMoney(ctx, in, opts...)
}

// userAddress
func (m *defaultUser) GetUserAddressList(ctx context.Context, in *GetUserAddressListReq, opts ...grpc.CallOption) (*GetUserAddressListResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserAddressList(ctx, in, opts...)
}

func (m *defaultUser) CreateUserAddress(ctx context.Context, in *CreateUserAddressReq, opts ...grpc.CallOption) (*CreateUserAddressResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CreateUserAddress(ctx, in, opts...)
}

func (m *defaultUser) UpdateUserAddress(ctx context.Context, in *UpdateUserAddressReq, opts ...grpc.CallOption) (*UpdateUserAddressResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateUserAddress(ctx, in, opts...)
}

func (m *defaultUser) DeleteUserAddress(ctx context.Context, in *DeleteUserAddressReq, opts ...grpc.CallOption) (*DeleteUserAddressResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.DeleteUserAddress(ctx, in, opts...)
}

func (m *defaultUser) GetUserAddressDetail(ctx context.Context, in *GetUserAddressDetailReq, opts ...grpc.CallOption) (*GetUserAddressDetailResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserAddressDetail(ctx, in, opts...)
}

// other
func (m *defaultUser) CheckUserExists(ctx context.Context, in *CheckUserExistsReq, opts ...grpc.CallOption) (*CheckUserExistsResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CheckUserExists(ctx, in, opts...)
}

func (m *defaultUser) CheckUserAndAddressExists(ctx context.Context, in *CheckUserAndAddressExistsReq, opts ...grpc.CallOption) (*CheckUserAndAddressExistsResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CheckUserAndAddressExists(ctx, in, opts...)
}

func (m *defaultUser) UpdateUserMoney(ctx context.Context, in *UpdateUserMoneyReq, opts ...grpc.CallOption) (*UpdateUserMoneyResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateUserMoney(ctx, in, opts...)
}
