// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	carouselFieldNames          = builder.RawFieldNames(&Carousel{})
	carouselRows                = strings.Join(carouselFieldNames, ",")
	carouselRowsExpectAutoSet   = strings.Join(stringx.Remove(carouselFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	carouselRowsWithPlaceHolder = strings.Join(stringx.Remove(carouselFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	carouselModel interface {
		Insert(ctx context.Context, data *Carousel) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Carousel, error)
		Update(ctx context.Context, data *Carousel) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCarouselModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Carousel struct {
		Id         int64     `db:"id"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
		DeleteTime time.Time `db:"delete_time"`
		DelState   int64     `db:"del_state"`
		ProductId  int64     `db:"product_id"`
		ImgPath    string    `db:"img_path"`
	}
)

func newCarouselModel(conn sqlx.SqlConn) *defaultCarouselModel {
	return &defaultCarouselModel{
		conn:  conn,
		table: "`carousel`",
	}
}

func (m *defaultCarouselModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCarouselModel) FindOne(ctx context.Context, id int64) (*Carousel, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", carouselRows, m.table)
	var resp Carousel
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCarouselModel) Insert(ctx context.Context, data *Carousel) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, carouselRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.ProductId, data.ImgPath)
	return ret, err
}

func (m *defaultCarouselModel) Update(ctx context.Context, data *Carousel) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, carouselRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.ProductId, data.ImgPath, data.Id)
	return err
}

func (m *defaultCarouselModel) tableName() string {
	return m.table
}
