// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productRecommendFieldNames          = builder.RawFieldNames(&ProductRecommend{})
	productRecommendRows                = strings.Join(productRecommendFieldNames, ",")
	productRecommendRowsExpectAutoSet   = strings.Join(stringx.Remove(productRecommendFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productRecommendRowsWithPlaceHolder = strings.Join(stringx.Remove(productRecommendFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	productRecommendModel interface {
		Insert(ctx context.Context, data *ProductRecommend) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ProductRecommend, error)
		Update(ctx context.Context, data *ProductRecommend) error
		Delete(ctx context.Context, id int64) error
	}

	defaultProductRecommendModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ProductRecommend struct {
		Id         int64     `db:"id"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
		DeleteTime time.Time `db:"delete_time"`
		DelState   int64     `db:"del_state"`  // 删除状态 0:未删除 1:已删除
		ProductId  uint64    `db:"product_id"` // 商品id
	}
)

func newProductRecommendModel(conn sqlx.SqlConn) *defaultProductRecommendModel {
	return &defaultProductRecommendModel{
		conn:  conn,
		table: "`product_recommend`",
	}
}

func (m *defaultProductRecommendModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProductRecommendModel) FindOne(ctx context.Context, id int64) (*ProductRecommend, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productRecommendRows, m.table)
	var resp ProductRecommend
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductRecommendModel) Insert(ctx context.Context, data *ProductRecommend) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, productRecommendRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.ProductId)
	return ret, err
}

func (m *defaultProductRecommendModel) Update(ctx context.Context, data *ProductRecommend) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productRecommendRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.ProductId, data.Id)
	return err
}

func (m *defaultProductRecommendModel) tableName() string {
	return m.table
}
