// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productImgFieldNames          = builder.RawFieldNames(&ProductImg{})
	productImgRows                = strings.Join(productImgFieldNames, ",")
	productImgRowsExpectAutoSet   = strings.Join(stringx.Remove(productImgFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productImgRowsWithPlaceHolder = strings.Join(stringx.Remove(productImgFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	productImgModel interface {
		Insert(ctx context.Context, data *ProductImg) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ProductImg, error)
		Update(ctx context.Context, data *ProductImg) error
		Delete(ctx context.Context, id int64) error
	}

	defaultProductImgModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ProductImg struct {
		Id         int64     `db:"id"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
		DeleteTime time.Time `db:"delete_time"`
		DelState   int64     `db:"del_state"` // 删除状态：0-未删除，1-已删除
		ProductId  int64     `db:"product_id"`
		Path       string    `db:"path"`      // 图片路径
		Type       int64     `db:"type"`      // 图片存储类型：1-本地存储，2-七牛云存储
		IsCover    int64     `db:"is_cover"`  // 是否为商品封面图片
		ImgOrder   int64     `db:"img_order"` // 图片排序
	}
)

func newProductImgModel(conn sqlx.SqlConn) *defaultProductImgModel {
	return &defaultProductImgModel{
		conn:  conn,
		table: "`product_img`",
	}
}

func (m *defaultProductImgModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProductImgModel) FindOne(ctx context.Context, id int64) (*ProductImg, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productImgRows, m.table)
	var resp ProductImg
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductImgModel) Insert(ctx context.Context, data *ProductImg) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, productImgRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.ProductId, data.Path, data.Type, data.IsCover, data.ImgOrder)
	return ret, err
}

func (m *defaultProductImgModel) Update(ctx context.Context, data *ProductImg) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productImgRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.ProductId, data.Path, data.Type, data.IsCover, data.ImgOrder, data.Id)
	return err
}

func (m *defaultProductImgModel) tableName() string {
	return m.table
}
