// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productCommentFieldNames          = builder.RawFieldNames(&ProductComment{})
	productCommentRows                = strings.Join(productCommentFieldNames, ",")
	productCommentRowsExpectAutoSet   = strings.Join(stringx.Remove(productCommentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productCommentRowsWithPlaceHolder = strings.Join(stringx.Remove(productCommentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	productCommentModel interface {
		Insert(ctx context.Context, data *ProductComment) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ProductComment, error)
		Update(ctx context.Context, data *ProductComment) error
		Delete(ctx context.Context, id int64) error
	}

	defaultProductCommentModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ProductComment struct {
		Id         int64     `db:"id"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
		DeleteTime time.Time `db:"delete_time"`
		DelState   int64     `db:"del_state"`   // 删除状态 0:未删除 1:已删除
		UserId     int64     `db:"user_id"`     // 用户id
		ProductId  int64     `db:"product_id"`  // 商品id
		IsGood     int64     `db:"is_good"`     // -1-差评，0-中性，1-好评
		Content    string    `db:"content"`     // 评论内容
		AddContent string    `db:"add_content"` // 追加评论内容
	}
)

func newProductCommentModel(conn sqlx.SqlConn) *defaultProductCommentModel {
	return &defaultProductCommentModel{
		conn:  conn,
		table: "`product_comment`",
	}
}

func (m *defaultProductCommentModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProductCommentModel) FindOne(ctx context.Context, id int64) (*ProductComment, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productCommentRows, m.table)
	var resp ProductComment
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductCommentModel) Insert(ctx context.Context, data *ProductComment) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, productCommentRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.UserId, data.ProductId, data.IsGood, data.Content, data.AddContent)
	return ret, err
}

func (m *defaultProductCommentModel) Update(ctx context.Context, data *ProductComment) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productCommentRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.UserId, data.ProductId, data.IsGood, data.Content, data.AddContent, data.Id)
	return err
}

func (m *defaultProductCommentModel) tableName() string {
	return m.table
}
