// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: order.proto

package orderclient

import (
	"context"

	"github.com/mirage208/gomall/app/order/rpc/pb/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateOrderResp        = order.CreateOrderResp
	CreateProductOrderReq  = order.CreateProductOrderReq
	CreateSeckillOrderReq  = order.CreateSeckillOrderReq
	DeleteOrderReq         = order.DeleteOrderReq
	DeleteOrderResp        = order.DeleteOrderResp
	GetOrderOnlyDetailReq  = order.GetOrderOnlyDetailReq
	GetOrderOnlyDetailResp = order.GetOrderOnlyDetailResp
	OrderDetailReq         = order.OrderDetailReq
	OrderDetailResp        = order.OrderDetailResp
	OrderListReq           = order.OrderListReq
	OrderListResp          = order.OrderListResp
	SmallOrder             = order.SmallOrder
	UpdateOrderStatusReq   = order.UpdateOrderStatusReq
	UpdateOrderStatusResp  = order.UpdateOrderStatusResp

	Order interface {
		CreateProductOrder(ctx context.Context, in *CreateProductOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error)
		CreateSeckillOrder(ctx context.Context, in *CreateSeckillOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error)
		OrderList(ctx context.Context, in *OrderListReq, opts ...grpc.CallOption) (*OrderListResp, error)
		OrderDetail(ctx context.Context, in *OrderDetailReq, opts ...grpc.CallOption) (*OrderDetailResp, error)
		DeleteOrder(ctx context.Context, in *DeleteOrderReq, opts ...grpc.CallOption) (*DeleteOrderResp, error)
		UpdateOrderStatus(ctx context.Context, in *UpdateOrderStatusReq, opts ...grpc.CallOption) (*UpdateOrderStatusResp, error)
		// other
		GetOrderOnlyDetail(ctx context.Context, in *GetOrderOnlyDetailReq, opts ...grpc.CallOption) (*GetOrderOnlyDetailResp, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

func (m *defaultOrder) CreateProductOrder(ctx context.Context, in *CreateProductOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CreateProductOrder(ctx, in, opts...)
}

func (m *defaultOrder) CreateSeckillOrder(ctx context.Context, in *CreateSeckillOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CreateSeckillOrder(ctx, in, opts...)
}

func (m *defaultOrder) OrderList(ctx context.Context, in *OrderListReq, opts ...grpc.CallOption) (*OrderListResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.OrderList(ctx, in, opts...)
}

func (m *defaultOrder) OrderDetail(ctx context.Context, in *OrderDetailReq, opts ...grpc.CallOption) (*OrderDetailResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.OrderDetail(ctx, in, opts...)
}

func (m *defaultOrder) DeleteOrder(ctx context.Context, in *DeleteOrderReq, opts ...grpc.CallOption) (*DeleteOrderResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.DeleteOrder(ctx, in, opts...)
}

func (m *defaultOrder) UpdateOrderStatus(ctx context.Context, in *UpdateOrderStatusReq, opts ...grpc.CallOption) (*UpdateOrderStatusResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.UpdateOrderStatus(ctx, in, opts...)
}

// other
func (m *defaultOrder) GetOrderOnlyDetail(ctx context.Context, in *GetOrderOnlyDetailReq, opts ...grpc.CallOption) (*GetOrderOnlyDetailResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.GetOrderOnlyDetail(ctx, in, opts...)
}
