// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"github.com/mirage208/gomall/app/product/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 产品创建
				Method:  http.MethodPost,
				Path:    "/api/product/create",
				Handler: CreateHandler(serverCtx),
			},
			{
				// 产品详情
				Method:  http.MethodPost,
				Path:    "/api/product/detail",
				Handler: DetailHandler(serverCtx),
			},
			{
				// 产品删除
				Method:  http.MethodPost,
				Path:    "/api/product/remove",
				Handler: RemoveHandler(serverCtx),
			},
			{
				// 产品修改
				Method:  http.MethodPost,
				Path:    "/api/product/update",
				Handler: UpdateHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
