// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: cart.proto

package cart

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CartProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=ProductId,proto3" json:"ProductId,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	Banner        string                 `protobuf:"bytes,4,opt,name=Banner,proto3" json:"Banner,omitempty"`
	Price         int64                  `protobuf:"varint,5,opt,name=Price,proto3" json:"Price,omitempty"`
	DiscountPrice int64                  `protobuf:"varint,6,opt,name=DiscountPrice,proto3" json:"DiscountPrice,omitempty"`
	Count         int64                  `protobuf:"varint,7,opt,name=Count,proto3" json:"Count,omitempty"`
	Checked       int64                  `protobuf:"varint,8,opt,name=Checked,proto3" json:"Checked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartProduct) Reset() {
	*x = CartProduct{}
	mi := &file_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartProduct) ProtoMessage() {}

func (x *CartProduct) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartProduct.ProtoReflect.Descriptor instead.
func (*CartProduct) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{0}
}

func (x *CartProduct) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartProduct) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CartProduct) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CartProduct) GetBanner() string {
	if x != nil {
		return x.Banner
	}
	return ""
}

func (x *CartProduct) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CartProduct) GetDiscountPrice() int64 {
	if x != nil {
		return x.DiscountPrice
	}
	return 0
}

func (x *CartProduct) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CartProduct) GetChecked() int64 {
	if x != nil {
		return x.Checked
	}
	return 0
}

type AddProductToCartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=ProductId,proto3" json:"ProductId,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=Count,proto3" json:"Count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductToCartReq) Reset() {
	*x = AddProductToCartReq{}
	mi := &file_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductToCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductToCartReq) ProtoMessage() {}

func (x *AddProductToCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductToCartReq.ProtoReflect.Descriptor instead.
func (*AddProductToCartReq) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{1}
}

func (x *AddProductToCartReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddProductToCartReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *AddProductToCartReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type AddProductToCartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductToCartResp) Reset() {
	*x = AddProductToCartResp{}
	mi := &file_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductToCartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductToCartResp) ProtoMessage() {}

func (x *AddProductToCartResp) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductToCartResp.ProtoReflect.Descriptor instead.
func (*AddProductToCartResp) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{2}
}

type CartProductListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartProductListReq) Reset() {
	*x = CartProductListReq{}
	mi := &file_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartProductListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartProductListReq) ProtoMessage() {}

func (x *CartProductListReq) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartProductListReq.ProtoReflect.Descriptor instead.
func (*CartProductListReq) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{3}
}

func (x *CartProductListReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CartProductListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartProducts  []*CartProduct         `protobuf:"bytes,1,rep,name=CartProducts,proto3" json:"CartProducts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartProductListResp) Reset() {
	*x = CartProductListResp{}
	mi := &file_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartProductListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartProductListResp) ProtoMessage() {}

func (x *CartProductListResp) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartProductListResp.ProtoReflect.Descriptor instead.
func (*CartProductListResp) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{4}
}

func (x *CartProductListResp) GetCartProducts() []*CartProduct {
	if x != nil {
		return x.CartProducts
	}
	return nil
}

type DeleteProductFromCartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	CartId        int64                  `protobuf:"varint,2,opt,name=CartId,proto3" json:"CartId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductFromCartReq) Reset() {
	*x = DeleteProductFromCartReq{}
	mi := &file_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductFromCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductFromCartReq) ProtoMessage() {}

func (x *DeleteProductFromCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductFromCartReq.ProtoReflect.Descriptor instead.
func (*DeleteProductFromCartReq) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteProductFromCartReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteProductFromCartReq) GetCartId() int64 {
	if x != nil {
		return x.CartId
	}
	return 0
}

type DeleteProductFromCartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductFromCartResp) Reset() {
	*x = DeleteProductFromCartResp{}
	mi := &file_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductFromCartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductFromCartResp) ProtoMessage() {}

func (x *DeleteProductFromCartResp) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductFromCartResp.ProtoReflect.Descriptor instead.
func (*DeleteProductFromCartResp) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{6}
}

type UpdateProductDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartId        int64                  `protobuf:"varint,1,opt,name=CartId,proto3" json:"CartId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=Count,proto3" json:"Count,omitempty"`
	Check         int64                  `protobuf:"varint,4,opt,name=Check,proto3" json:"Check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductDetailReq) Reset() {
	*x = UpdateProductDetailReq{}
	mi := &file_cart_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductDetailReq) ProtoMessage() {}

func (x *UpdateProductDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductDetailReq.ProtoReflect.Descriptor instead.
func (*UpdateProductDetailReq) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProductDetailReq) GetCartId() int64 {
	if x != nil {
		return x.CartId
	}
	return 0
}

func (x *UpdateProductDetailReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateProductDetailReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *UpdateProductDetailReq) GetCheck() int64 {
	if x != nil {
		return x.Check
	}
	return 0
}

type UpdateProductDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductDetailResp) Reset() {
	*x = UpdateProductDetailResp{}
	mi := &file_cart_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductDetailResp) ProtoMessage() {}

func (x *UpdateProductDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductDetailResp.ProtoReflect.Descriptor instead.
func (*UpdateProductDetailResp) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{8}
}

var File_cart_proto protoreflect.FileDescriptor

const file_cart_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"cart.proto\x12\x04cart\"\xd5\x01\n" +
	"\vCartProduct\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x1c\n" +
	"\tProductId\x18\x02 \x01(\x03R\tProductId\x12\x14\n" +
	"\x05Title\x18\x03 \x01(\tR\x05Title\x12\x16\n" +
	"\x06Banner\x18\x04 \x01(\tR\x06Banner\x12\x14\n" +
	"\x05Price\x18\x05 \x01(\x03R\x05Price\x12$\n" +
	"\rDiscountPrice\x18\x06 \x01(\x03R\rDiscountPrice\x12\x14\n" +
	"\x05Count\x18\a \x01(\x03R\x05Count\x12\x18\n" +
	"\aChecked\x18\b \x01(\x03R\aChecked\"a\n" +
	"\x13AddProductToCartReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x1c\n" +
	"\tProductId\x18\x02 \x01(\x03R\tProductId\x12\x14\n" +
	"\x05Count\x18\x03 \x01(\x03R\x05Count\"\x16\n" +
	"\x14AddProductToCartResp\",\n" +
	"\x12CartProductListReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\"L\n" +
	"\x13CartProductListResp\x125\n" +
	"\fCartProducts\x18\x01 \x03(\v2\x11.cart.CartProductR\fCartProducts\"J\n" +
	"\x18DeleteProductFromCartReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x16\n" +
	"\x06CartId\x18\x02 \x01(\x03R\x06CartId\"\x1b\n" +
	"\x19DeleteProductFromCartResp\"t\n" +
	"\x16UpdateProductDetailReq\x12\x16\n" +
	"\x06CartId\x18\x01 \x01(\x03R\x06CartId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\x12\x14\n" +
	"\x05Count\x18\x03 \x01(\x03R\x05Count\x12\x14\n" +
	"\x05Check\x18\x04 \x01(\x03R\x05Check\"\x19\n" +
	"\x17UpdateProductDetailResp2\xc7\x02\n" +
	"\x04cart\x12I\n" +
	"\x10addProductToCart\x12\x19.cart.AddProductToCartReq\x1a\x1a.cart.AddProductToCartResp\x12F\n" +
	"\x0fcartProductList\x12\x18.cart.CartProductListReq\x1a\x19.cart.CartProductListResp\x12X\n" +
	"\x15deleteProductFromCart\x12\x1e.cart.DeleteProductFromCartReq\x1a\x1f.cart.DeleteProductFromCartResp\x12R\n" +
	"\x13updateProductDetail\x12\x1c.cart.UpdateProductDetailReq\x1a\x1d.cart.UpdateProductDetailRespB\bZ\x06./cartb\x06proto3"

var (
	file_cart_proto_rawDescOnce sync.Once
	file_cart_proto_rawDescData []byte
)

func file_cart_proto_rawDescGZIP() []byte {
	file_cart_proto_rawDescOnce.Do(func() {
		file_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cart_proto_rawDesc), len(file_cart_proto_rawDesc)))
	})
	return file_cart_proto_rawDescData
}

var file_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cart_proto_goTypes = []any{
	(*CartProduct)(nil),               // 0: cart.CartProduct
	(*AddProductToCartReq)(nil),       // 1: cart.AddProductToCartReq
	(*AddProductToCartResp)(nil),      // 2: cart.AddProductToCartResp
	(*CartProductListReq)(nil),        // 3: cart.CartProductListReq
	(*CartProductListResp)(nil),       // 4: cart.CartProductListResp
	(*DeleteProductFromCartReq)(nil),  // 5: cart.DeleteProductFromCartReq
	(*DeleteProductFromCartResp)(nil), // 6: cart.DeleteProductFromCartResp
	(*UpdateProductDetailReq)(nil),    // 7: cart.UpdateProductDetailReq
	(*UpdateProductDetailResp)(nil),   // 8: cart.UpdateProductDetailResp
}
var file_cart_proto_depIdxs = []int32{
	0, // 0: cart.CartProductListResp.CartProducts:type_name -> cart.CartProduct
	1, // 1: cart.cart.addProductToCart:input_type -> cart.AddProductToCartReq
	3, // 2: cart.cart.cartProductList:input_type -> cart.CartProductListReq
	5, // 3: cart.cart.deleteProductFromCart:input_type -> cart.DeleteProductFromCartReq
	7, // 4: cart.cart.updateProductDetail:input_type -> cart.UpdateProductDetailReq
	2, // 5: cart.cart.addProductToCart:output_type -> cart.AddProductToCartResp
	4, // 6: cart.cart.cartProductList:output_type -> cart.CartProductListResp
	6, // 7: cart.cart.deleteProductFromCart:output_type -> cart.DeleteProductFromCartResp
	8, // 8: cart.cart.updateProductDetail:output_type -> cart.UpdateProductDetailResp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cart_proto_init() }
func file_cart_proto_init() {
	if File_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cart_proto_rawDesc), len(file_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cart_proto_goTypes,
		DependencyIndexes: file_cart_proto_depIdxs,
		MessageInfos:      file_cart_proto_msgTypes,
	}.Build()
	File_cart_proto = out.File
	file_cart_proto_goTypes = nil
	file_cart_proto_depIdxs = nil
}
