Name: product.rpc
ListenOn: 0.0.0.0:9002
# Etcd:
#   Hosts:
#   - 127.0.0.1:2379
#   Key: product.rpc

# RPC Metrics配置
DevServer:
  Enabled: true
  Port: 6012
  MetricsPath: /metrics
  EnableMetrics: true

Mysql:
  DataSource: mysql_dev:MysqlDev#@tcp(rm-cn-x4t4dacrk0002fvo.rwlb.rds.aliyuncs.com:3306)/mall?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

CacheRedis:
- Host: r-uf6xro0hktcq0czhdwpd.redis.rds.aliyuncs.com:6379
  Type: node
  User: redis_dev
  Pass: SuperDev#
